## 接口请求

- 之前一般请求方式只会用到 GET、POST，传参的时候一般是 http://www.baidu.com?name=xxx&age=18

- RESTFul API，请求方式更语义化（更具体了），传参方式变了 http://www.baidu.com/xxx/18

## 异步请求的问题

假如下一次的请求需要**依赖**上一次的返回结果，必须嵌套，层层嵌套下去，代码变得很难维护且不优雅，这种我们称为==1. 回调地狱==

```js
// 后端代码
app.get('/data1', (req, res) => {
    res.send('data2')
});
app.get('/data2', (req, res) => {
    res.send('data3')
});
app.get('/data3', (req, res) => {
    res.send('Finish')
});
```

```js
// 前端代码
$.ajax({
    url: 'http://localhost:3000/data1',
    success: function (data) {
        // data => 'data2'
        $.ajax({
            url: `http://localhost:3000/${data}`,
            success: function (data) {
                // data => 'data3'
                $.ajax({
                    url: `http://localhost:3000/${data}`,
                    success: function (data) {
                        console.log(data)
                    }
                });
            }
        });
    }
});
```

## 解决方案

==Promise==（本质上是一个对象/方法），ES6 新出的用来解决回调地狱的一种编码方案

- 基本使用

```js
// 这里作为一个构造函数使用的，需要 new 一下
// 接收的参数是一个函数，函数里面又有两个参数
// 第 1 个参数是 resolve（解决），代表成功之后需要调用的方法
// 第 2 个参数是 reject（拒绝），代表失败之后需要调用的方法
const p = new Promise((resolve, reject) => {
    setTimeout(() => {
        if (Math.random() > 0.5) {
            // 这里可以传递成功之后的参数的
            resolve('成功');
        } else {
            // 这里可以传递失败之后的参数的
            reject('失败');
        }
    }, 1000);
});

// 要想拿到成功或失败之后的结果（就是resolve或者reject传递的参数），要通过 then
// then 里面也有两个参数，这两个参数都是函数，函数里面的参数就代表成功或失败的内容，说白了就是 resolve 或 reject 传递过来的参数
p.then(data => {
    // 成功就会走这里
    console.log(data);
}, err => {
    // 失败就会走这里
    console.log(err);
});
```

- ==2. 用 Promise 改造上面回调地狱的代码==

Promise 确确实实可以解决回调地狱的问题，但是也确实不能简化代码，怎么又能解决回到地狱，又能简化代码呢？后面的 async/await

```js
function rq(path) {
    return new Promise((resolve, reject) => {
        $.ajax({
            url: `http://192.168.85.138:3000/${path}`,
            success: function (data) {
                // 成功之后，调用 resolve，把后端返回的真正的数据传递出去
                resolve(data);
            },
            error: function(err) {
                // 失败之后，就把错误对象传递出去
                reject(err);
            }
        });
    });
}
// 这个函数调用完后，拿到的结果就是 Promise 实例，是 Promise 就有 then 方法
rq('data1').then(data => {
    // 这个 data 就是成功之后拿到的结果呀
    // console.log(data);
    // rq(data) => 这个调用完后返回的也是 Promise 呀
    // 我又把这个 Promise 返回啦，返回之后可以继续通过 then 拿到这一次 resolve 的结果
    return rq(data);
    // 不要下面的写法，直接通过上面形式返回
    /*  rq(data).then(data => {                                                    
        rq(data).then(data => {
            console.log(data);
        })
    }) */
}).then(data => {
    return rq(data);
}).then(data => {
    console.log(data);
}).catch(err => {
    // 只要前面的操作有一个出错了就会走这里的 catch
    console.log('出错啦', err.statusText);
});
```

## 静态方法

```js
Promise.all([rq('data1'), rq('data2'), rq('data3')]).then(result => {
    console.log(result);
});
```

```js
// AJAX 实际上来说也支持 Promise 的写法，了解一下
/* $.ajax({
    url: `http://localhost:3000/data1`,
    success: function (data) {
        // 成功之后，调用 resolve，把后端返回的真正的数据传递出去
        console.log(data);
    }
}); */
$.ajax({
    url: `http://localhost:3000/data1`,
}).then(data => {
    console.log(data);
});
```

## 再举个例子

- 拿不到结果

```js
const sum = (a, b) => {
    setTimeout(() => {
        return a + b;
    }, 1000);
};
const r = sum(5, 8);
console.log(r); // undefined
```

- 解决方案1：回调函数

```js
// 如何拿到函数里面的异步结果呢？
const sum = (a, b, c) => {
    setTimeout(() => {
        let sum = a + b;
        // 调用函数，并且传递处理之后的结果
        c(sum);
    }, 1000);
};
sum(5, 8, function(r) {
    console.log(r);
});
```

- 解决方案2：Promise

```js
const sum = (a, b) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            let sum = a + b;
            // 调用 resolve，把成功之后的结果怼出去
            resolve(sum);
        }, 1000);
    });
};
// sum(5, 8) 调用完之后得到的返回值就是 Promise 实例，是 Promise 就有 then
sum(5, 8).then(res => {
    console.log(res);
});
```

- 其实只有一个异步的话，不必要用 async/await

```js
const sum = (a, b) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            let sum = a + b;
            // 调用 resolve，把成功之后的结果怼出去
            resolve(sum);
        }, 1000);
    });
};

;(async () => {
    console.log(await sum(5, 8));
})();
```

## Fetch

浏览器提供的也是用来请求数据的 API，可以替代 XMLHttpRequest 对象

```js
// 如果说后端返回的是一个字符串类型的数据，需要调用 text() 进行处理一下
// 处理之后的结果还是一个 Promise，把这个 Promise 返回之后，就可以通过下次的 then 拿到真正的结果啦
fetch('http://localhost:3000/data1').then(data => data.text()).then(data => {
    console.log(data);
});
```

## Aysnc/Await 异步的终极解决方案

- async 修饰的函数我们称为是一个异步函数，这个异步函数调用后的返回值是一个 Promise

- async 修饰普通函数和箭头函数，注意写的位置

- await 必须放到 async 函数里面

- await 后面一般要跟一个 Promise，await 后的返回值就是 Promise resolve 的结果

```js
// 普通函数 async 写在了 function 前面
/* async function test() {
    return 'Hello world';
}
test().then(res => console.log(res)); */

// 箭头函数，async 写在了 () 前面
const test = async () => {
    return 'Hello world';
};
test().then(res => console.log(res));
```

**基本用法**

```js
/* function test() {
    return 'hello';
}
console.log(test()); // 'hello' */

// 下面是一个异步函数，因为用 async 修饰了
async function test() {
    // return Promise.resolve('hello');
    // 下面写法，实际上来说和上面代码一样
    return 'hello';
}
// 这个异步函数调用后的返回值是一个 Promise
// 是 Promise 就有 then
test().then(data => {
    console.log(data);
});
```

- 用 async/await 改写一个普通的请求

```js
// 这就是一个普通的请求
axios.get('adata').then(function (ret) {
    console.log(ret.data)
})
```

```js
// 用 async/await 改写上面的代码
async function queryData() {
    // await 之后的返回值，就是这个 Promise 成功之后的结果
    let ret = await axios.get('adata');
    // console.log(ret.data)
    // 函数封装有一个原则：不要替调用者决定做什么事情
    return ret.data;
}
// queryData 是一个异步函数，返回结果是一个 Promise
queryData().then(res => {
    console.log(res);
});
```

- ==3. 用 async 继续改写前面的 Promise 请求==

```js
function rq(path) {
    return new Promise((resolve, reject) => {
        $.ajax({
            url: `http://localhost:3000/${path}`,
            success: function (data) {
                // 成功之后，调用 resolve，把后端返回的真正的数据传递出去
                resolve(data);
            },
            error: function (err) {
                // 失败之后，就把错误对象传递出去
                reject(err);
            }
        });
    });
}
// rq('data1').then(data => {
//     return rq(data);
// }).then(data => {
//     return rq(data);
// }).then(data => {
//     console.log(data);
// }).catch(err => {
//     // 只要前面的操作有一个出错了就会走这里的 catch
//     console.log('出错啦', err.statusText);
// });

// 妙处就在：可以以同步的形式，写异步的代码
/* const getCon = async () => {
    // await 后面一般要跟一个 Promise，await 后的返回值就是 Promise resolve 的结果
    const r1 = await rq('data1'); // 'data2'
    const r2 = await rq(r1); // 'data3'
    const r3 = await rq(r2); // 'Finish'
    console.log(r3);
};
getCon(); */

;(async () => {
    const r1 = await rq('data1'); // 'data2'
    const r2 = await rq(r1); // 'data3'
    const r3 = await rq(r2); // 'Finish'
    console.log(r3);
})();
```

